//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltoonTTS2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchApi {
            get {
                return ((string)(this["TwitchApi"]));
            }
            set {
                this["TwitchApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchID {
            get {
                return ((string)(this["TwitchID"]));
            }
            set {
                this["TwitchID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchNickname {
            get {
                return ((string)(this["TwitchNickname"]));
            }
            set {
                this["TwitchNickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveEmoji {
            get {
                return ((bool)(this["RemoveEmoji"]));
            }
            set {
                this["RemoveEmoji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstalledVoiceSelect {
            get {
                return ((string)(this["InstalledVoiceSelect"]));
            }
            set {
                this["InstalledVoiceSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TtsVolumeValue {
            get {
                return ((int)(this["TtsVolumeValue"]));
            }
            set {
                this["TtsVolumeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TtsSpeedValue {
            get {
                return ((int)(this["TtsSpeedValue"]));
            }
            set {
                this["TtsSpeedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectToTwitch {
            get {
                return ((bool)(this["ConnectToTwitch"]));
            }
            set {
                this["ConnectToTwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxDoNotTtsIfStartWith {
            get {
                return ((string)(this["TextBoxDoNotTtsIfStartWith"]));
            }
            set {
                this["TextBoxDoNotTtsIfStartWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxMessageSkip {
            get {
                return ((string)(this["TextBoxMessageSkip"]));
            }
            set {
                this["TextBoxMessageSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxMessageSkipAll {
            get {
                return ((string)(this["TextBoxMessageSkipAll"]));
            }
            set {
                this["TextBoxMessageSkipAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoodgameNickname {
            get {
                return ((string)(this["GoodgameNickname"]));
            }
            set {
                this["GoodgameNickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectToGoodgame {
            get {
                return ((bool)(this["ConnectToGoodgame"]));
            }
            set {
                this["ConnectToGoodgame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BlackListMembers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlackListMembers"]));
            }
            set {
                this["BlackListMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WhatToReplace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WhatToReplace"]));
            }
            set {
                this["WhatToReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WhatToReplaceWith {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WhatToReplaceWith"]));
            }
            set {
                this["WhatToReplaceWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IndividualVoicesEnabled {
            get {
                return ((bool)(this["IndividualVoicesEnabled"]));
            }
            set {
                this["IndividualVoicesEnabled"] = value;
            }
        }
    }
}
