//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltoonTTS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchApi {
            get {
                return ((string)(this["TwitchApi"]));
            }
            set {
                this["TwitchApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchID {
            get {
                return ((string)(this["TwitchID"]));
            }
            set {
                this["TwitchID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchNickname {
            get {
                return ((string)(this["TwitchNickname"]));
            }
            set {
                this["TwitchNickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveEmoji {
            get {
                return ((bool)(this["RemoveEmoji"]));
            }
            set {
                this["RemoveEmoji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string InstalledVoiceSelect {
            get {
                return ((string)(this["InstalledVoiceSelect"]));
            }
            set {
                this["InstalledVoiceSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TtsVolumeValue {
            get {
                return ((int)(this["TtsVolumeValue"]));
            }
            set {
                this["TtsVolumeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TtsSpeedValue {
            get {
                return ((int)(this["TtsSpeedValue"]));
            }
            set {
                this["TtsSpeedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IndividualVoices {
            get {
                return ((bool)(this["IndividualVoices"]));
            }
            set {
                this["IndividualVoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckboxConnectToTwitch {
            get {
                return ((bool)(this["CheckboxConnectToTwitch"]));
            }
            set {
                this["CheckboxConnectToTwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxDoNotTtsIfStartWith {
            get {
                return ((string)(this["TextBoxDoNotTtsIfStartWith"]));
            }
            set {
                this["TextBoxDoNotTtsIfStartWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxMessageSkip {
            get {
                return ((string)(this["TextBoxMessageSkip"]));
            }
            set {
                this["TextBoxMessageSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxMessageSkipAll {
            get {
                return ((string)(this["TextBoxMessageSkipAll"]));
            }
            set {
                this["TextBoxMessageSkipAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxGoodgameLogin {
            get {
                return ((string)(this["TextBoxGoodgameLogin"]));
            }
            set {
                this["TextBoxGoodgameLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxGoodgamePassword {
            get {
                return ((string)(this["TextBoxGoodgamePassword"]));
            }
            set {
                this["TextBoxGoodgamePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckBoxConnectToGoodgame {
            get {
                return ((bool)(this["CheckBoxConnectToGoodgame"]));
            }
            set {
                this["CheckBoxConnectToGoodgame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxIndividualVoicesChannelPoints {
            get {
                return ((string)(this["TextBoxIndividualVoicesChannelPoints"]));
            }
            set {
                this["TextBoxIndividualVoicesChannelPoints"] = value;
            }
        }
    }
}
